version: "3.8"

services:
  # sqlserver:
  #   container_name: sqlserver
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   environment:
  #     MSSQL_SA_PASSWORD: "1236fG543$"
  #     ACCEPT_EULA: "Y"
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sql_data:/var/opt/mssql
  #   restart: always

  sa-api:
    container_name: SavingAccount-BETest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - UsersDatabase=Server=terraform-20241224223851745300000002.cpum2cwaojn4.ap-southeast-2.rds.amazonaws.com;Database=SavingAccount;User Id=admin;Password=SecurePass123!;TrustServerCertificate=True
    ports:
      - "8080:80"
    # depends_on:
    #   - sqlserver
    restart: always
    command: ["dotnet", "ef", "database update"]
# volumes:
#   sql_data:
#     name: sql_data
